### ISSUE TITLE
Incorrect timestamps for Apple watch processed motion

### ISSUE THREAD

**Issue by Gevrai** [introlab/OpenIMU#22]
There is an exactly one minute gap every hour in the timeline of imported 'ProcessedMotion' data. I've checked in the log files for error, but these gaps are not present in the data.

![image](https://user-images.githubusercontent.com/9045357/45794573-5a72ec80-bc65-11e8-902f-ac69405a160d.png)

I highly suspect that there is a problem with the code at '[AppleWatchImporter.py:738](https://github.com/introlab/OpenIMU/blob/master/python/libopenimu/importers/AppleWatchImporter.py#L738)', namely the comparison `timestamp_sec > last_timestamp + 3600` is for an hour, however I don't quite understand the import process to make a fix.

I can send you sample data if you wish, but any watch_ProcessedMotion.data file greater than 20Mb will show this behavior.

**Comment by doumdi** [comment]
Hello @Gevrai, can you send us a sample file so we can experiment with the problem. Thanks.

**Comment by Gevrai** [comment]
[Here is the file](https://www.dropbox.com/s/evx2ccqdt9awaaz/watch_ProcessedMotion.data?dl=0) used for the aforementioned timeline.

**Comment by doumdi** [comment]
@Gevrai I have looked at your file and it seems there is not a constant data rate for motion. If I look at each seconds I sometimes have : 
1537012811  has motion of size:  51
1537012812  has motion of size:  50
1537012813  has motion of size:  50
1537012814  has motion of size:  51
1537012815  has motion of size:  50
1537012816  has motion of size:  50
1537012817  has motion of size:  50
1537012818  has motion of size:  51
**1537012819  has motion of size:  19**
1537012820  has motion of size:  51
1537012821  has motion of size:  50
1537012822  has motion of size:  50

It happens often that we get a random number of samples under the sampling rate of 50. Any idea why?

**Comment by doumdi** [comment]
I haved pushed some debug prints in dev branch to show that. Also, right now we are creating one row per second for the sensor, which is way to many. That is why the intented way to store data in the database was one row per hour.

**Comment by Gevrai** [comment]
There is a 'bug' in the AppleWatch logger that we accepted to not change in which the samples that we receive are sometimes out of order. Only the Processed and Raw motion sensors are affected by this behavior. It is caused by the system sometimes putting the application to sleep for a fraction of a second, during which it stacks the samples, later sending the newer sample first (LIFO). Hence, right after those sleeps, we get samples in the reverse order.

From my tests, the random number of samples you are describing seem to happen right after those hiccups. I could fix it from the Apple Watch, I think the processing cost would be negligible if implemented correctly, or it could be done upon importation into OpenIMU. I think fixing on the logger itself is better, and could push a fix by the end of the week for this.

This bug however does not explain the one minute gap every hour in the timeline, as no gap of more than a second are present in the sent data set.

**Comment by doumdi** [comment]
I agree with you, the "out-of-order" problem should be fixed on the device. It might probably be solved by buffering data before writing to file. There is absolutely a bug in the OpenIMU software that I will investigate further. Could you send us a new log when you have fixed the "out-of-order" issue please?

**Comment by Gevrai** [comment]
Sure, I'll try to fix it and send a new log file by the end of the week.

**Comment by Gevrai** [comment]
Bad news, fixing this would prove to need a buffer way bigger than expected. I was misdirected into my previous explanation of the behavior. After further analysis of the data, I found that there are random old data being sent by the system that was not previously sent for an unknown reason, sometimes as much as 10seconds later. Also, sometimes the AppleWatch simply don't send some points. I've decided to let it be on the logger and sort it upon import. [This](https://github.com/introlab/OpenIMU/pull/23) pull request fixes those out-of-order issues, but of course not the holes.

However, I haven't been able to fix the minute long holes. On this note, why aren't the precise timestamps in ms not kept anywhere in the db. I'd think that stripping the data of those would probably create holes like we see in the data if the sampling_rate is not exactly precise, which it probably isn't.

**Comment by doumdi** [comment]
Thanks for the pull request. It is rather strange that you get "outdated" information though. Maybe you should send Apple a bug report or ask other developers if they experience such problems on the Apple developer's forums.

As for timestamps, the initial goal was to avoid storing timestamps in the database that can be calculated / extracted by other means. However, I probably assumed "cleaner" time series and we should probably think of a way to store timestamps with data to avoid problems.

**Comment by SBriere** [comment]
Fixed when we added timestamps (Refs #27) to each data sample in the database.
