### ISSUE TITLE
Data visualization QoL modifications

### ISSUE THREAD

**Issue by Gevrai** [introlab/OpenIMU#24]
Here are the feature requests for improving the data visualization UI

- [x] Don't freeze UI on sensor selection
  - As of now, the UI freezes for a good 5 seconds before showing a graph with a lot of points
  - Should directly show the panel with a 'loading' icon, and do fetch in the background
- [x] Zoom and move on the main timeline
- [x] Access value(s) of sensor(s) for a precise timestamp
  - Upon selecting a precise timestamp on timeline and/or graph
  - Maybe even simply a label on mouse location (showing sensor name and data at point)
- [x] Easier correlation between timeline and sensor
  - Current color scheme is very hard to differentiate with 5+ sensor
  - A simple label when the mouse is over a precise timeline would help a lot
- [ ] Add option to pop (and re-embed) data graphs into a new window to permit a full screen visualization. 
  - The current bottom right panel uses maximum 50% of the screen real estate
  - Normally easy to implement, as the user is tasked with window management
- [ ] Give possibility to overlap 2+ sensors on the same graph

**Comment by SBriere** [comment]
>  Add option to pop (and re-embed) data graphs into a new window to permit a full screen visualization.

Current implementation in the dev branch allows the user to resize the usable area of a graph by hiding the left and top panels, allowing for almost full screen display.
 
> Give possibility to overlap 2+ sensors on the same graph

This won't be implemented for now as it would require physical units to match (e.g. "g" with "g" and "deg/s" with "deg/s") restraining the use of this functionality to very specific cases and such an overlapped graph usefulness is quite limited in real-life applications (i.e. not in a testing scenario). This might be something to be considered in the future if specific scenarios require such an overlap.
