### ISSUE TITLE
Cleanup main UI thread

### ISSUE THREAD

**Issue by Gevrai** [introlab/OpenIMU#25]
Currently, any long running operation freezes up the UI. Moving all of those (DB operation, data graphing, data imports) on a background thread would relieve the main thread and make the application snappier. One other benefit is that if a background thread crashes, it doesn't crash the whole application with it.

This will require a refactoring of the data and operation flow in the application, but will ultimately make it more modular and maintainable.

**Comment by SBriere** [comment]
Fixed for most operations - graph refresh are still hanging the UI, but that will be a different issue than this one.
