### ISSUE TITLE
Batch import with special meta-importation file

### ISSUE THREAD

**Issue by Gevrai** [introlab/OpenIMU#29]
Add support for batching an import with minimal user interaction, either from a predefined meta-session batcher, or by intelligent directory crawling, or a combination of both (directory crawling to find batchers).

Draft for formatting of an OpenIMU Meta-Import (.oimi :smiley:) with JSON formatting:
```
{
  "version" : "1"
  "logger_type" : "AppleWatch",
  "deviceID" : "W01P1",
  "appVersion" : "0.11.2",
  "participant" : "abcd1234",
  "description" : "any additional info on session? optional",
  "files" : [
    "watch_Battery.data",
    "watch_Coordinates.data",
    ...
  ]
}
```

**Comment by SBriere** [comment]
For the .oimi file format, would it possible to add the following informations (which will soon be added into OpenIMU)?

- Device software version used to collect the data
- Device ID (not sure if that information is available or not, but the idea would be to attach a specific device to a recordset)

**Comment by Gevrai** [comment]
Done in last version of SensorLogger on AppleWatch (0.11.3). Updated description in original comment.

For the device ID, I put the given name of the device (eg. W01P1), I don't seem to have access to the real device ID. This should be enough however.
