### ISSUE TITLE
ModuleNotFoundError: No module named 'resources.ui.python

### ISSUE THREAD

**Issue by filipeosalles** [introlab/OpenIMU#56]
Hello, 

My name is Filipe Salles and I'm working at Porto University, Portugal (indeed everyone is working at home during these quarantine times). I'm trying to install it, but I had a problem. When PyCharm is running, it shows up the following:

/usr/bin/python3.6 /home/salles/Documentos/OpenIMU-master/python/OpenIMUApp.py
Traceback (most recent call last):
  File "/home/salles/Documentos/OpenIMU-master/python/OpenIMUApp.py", line 409, in <module>
    from libopenimu.qt.MainWindow import MainWindow
  File "/home/salles/Documentos/OpenIMU-master/python/libopenimu/qt/MainWindow.py", line 12, in <module>
    from resources.ui.python.MainWindow_ui import Ui_MainWindow
ModuleNotFoundError: No module named 'resources.ui.python'
Process finished with exit code 1.

Anyone can help me with this? Thanks.

PS - It's my first time using Qt Creator and PyCharm (in ubuntu), so I think that maybe I did simething wrong in these parts.

**Comment by SBriere** [comment]
Hello Filipe,

Resources needs to be generated using cmake and Qt Creator. If you follow the steps in the ReadMe, this requires you to open the "CMakeLists.txt" file from the Qt Creator IDE and to build the project. This should create the missing files. 

Make sure that you have CMake correctly installed and configured before trying to build in Qt Creator.

Basically, we are building the User Intertace in Qt Creator and uses it to generate UI definitions in Python.

You might have some issues occuring in Ubuntu with capitals letters in files. We do most of our development in Windows and Mac environment, which are less sensible to cases, and while we tested in Linux some time ago, we haven't done so in the latest revisions. If you fix anything there, don't hesitate to submit a fix!

If you have access to a Windows or Mac machine, you could also try the versions we released for those OS in the release section: https://github.com/introlab/OpenIMU/releases

Please be aware also that, currently, we only have a French version of the software.
