### ISSUE TITLE
No python files getting generated after build in Qt

### ISSUE THREAD

**Issue by satishvaishnav** [introlab/OpenIMU#57]
The python/env/python-3.7 folder gets created but no files are generated within the folder. Although the build goes successful.

System: Macbook Pro 
OS: Catalina

**Comment by doumdi** [comment]
Make sure you build the target "python-all" to generate the environment.

**Comment by doumdi** [comment]
I have updated the main Readme.md file to add this information. Thanks for reporting the issue.

**Comment by satishvaishnav** [comment]
@doumdi Thank you. It gets build now properly. I appreciate it.
