### ISSUE TITLE
no error with build, but have fail to run

### ISSUE THREAD

**Issue by cryoguy** [introlab/OpenIMU#58]
Got the following error when run from pyCharm. Any pointer?

```
Traceback (most recent call last):
  File "/home/tan/proj/imu/OpenIMU/python/OpenIMUApp.py", line 409, in <module>
    from libopenimu.qt.MainWindow import MainWindow
  File "/home/tan/proj/imu/OpenIMU/python/libopenimu/qt/MainWindow.py", line 12, in <module>
    from resources.ui.python.MainWindow_ui import Ui_MainWindow
ModuleNotFoundError: No module named 'resources.ui.python.MainWindow_ui'Traceback (most recent call last):
  File "/home/tan/proj/imu/OpenIMU/python/OpenIMUApp.py", line 409, in <module>
    from libopenimu.qt.MainWindow import MainWindow
  File "/home/tan/proj/imu/OpenIMU/python/libopenimu/qt/MainWindow.py", line 12, in <module>
    from resources.ui.python.MainWindow_ui import Ui_MainWindow
ModuleNotFoundError: No module named 'resources.ui.python.MainWindow_ui'
```

**Comment by doumdi** [comment]
@cryoguy, You need to build the target "python-all" after generating the project with CMake. This will generate all the python UI files required to run.

**Comment by cryoguy** [comment]
I am getting the following error now.  It should work with python 3.7, right?

` from PyQt5.QtChart import QChart, QChartView, QLineSeries, QBarSeries, QBarSet
ModuleNotFoundError: No module named 'PyQt5.QtChart'`

**Comment by doumdi** [comment]
@cryoguy Make sure you are using the python interpreter in the virtual environment in python/env/python-3.7/bin. PYTHON_PATH must be the python directory, this is automatically set when using PyCharm. Must be set manually if you use Visual Studio Code.

**Comment by cryoguy** [comment]
@doumdi Thanks for your help.  I am using PyCharm, but I have to set the path manually. For some reason, I am still getting the same error!

![imu](https://user-images.githubusercontent.com/12690537/106933173-7a3bcb80-66cd-11eb-9654-cf3d0620c640.png)
